FROM python:3.12-slim

USER root

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
 && rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copy only requirements.txt
COPY src/requirements.txt /requirements.txt

RUN pip install --no-cache-dir -r /requirements.txt

# CMD ["tail", "-f", "/dev/null"]
CMD ["bash", "-c", "uvicorn api_main:app --host 0.0.0.0 --port 8000 --reload"]
